server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # We use manual routes for better control
          lower-case-service-id: true
      
      # Global CORS Configuration (Allow frontend access)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        # --- USER SERVICE ---
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        # --- FLIGHT SERVICE ---
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flights/**

        # --- AIRLINE SERVICE ---
        - id: airline-service
          uri: lb://airline-service
          predicates:
            - Path=/airlines/**

        # --- BOOKING SERVICE ---
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**

        # --- NOTIFICATION SERVICE ---
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}


#spring.application.name=api-gateway
#server.port=8080

#eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

##spring.cloud.gateway.discovery.locator.enabled=false
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true


#management.endpoints.web.exposure.include=*

## security
#jwt.secret=${JWT_SECRET}
